### ISSUE TITLE
How to write condition that polls until field with given value is missing

### ISSUE THREAD

**Issue by wojda** [kopf/httsleep#16]
In my case I create a job and want to poll until that job has completed. There is only one endpoint and it gives me the list of jobs that are in progress. If my job is not on the list - it's completed. Example response body:
```
[
   {"id": 1}, {"id": 2}, {"id": 3}
]
```
I want to poll until returned json does not contain my id.  Any idea how can I write that condition?

**Comment by kopf** [comment]
Hi,

in a case like this, I would suggest using a callback function. Something like the following:

```
class MyChecker(object):
    def __init__(self, id_):
        self.id_ = id_

    def job_not_present(self, response):
        data = response.json()
        # Return true if our job has disappeared from the response:
        return {'id': self.id_} not in data


def my_function():
    job = create_job()
    job_id = job.id
    checker = MyChecker(job_id)
    httsleep('http://myendpoint/', until={'callback': checker.job_not_present})
```

No idea if this works, I just threw it together now and didn't bother running/testing it, but hopefully it'll help you as a starting point.
