### ISSUE TITLE
Dict comprehensions don't work in Python 2.6

### ISSUE THREAD

**Issue by dofine** [kopf/httsleep#5]
I know Python 2.6 is quite an old version :)
But dict comprehensions doesn't appear until Python 2.7, so below from `main.py` Line 81 would fail:

`until.append({k: v for k, v in condition.items() if v})`

Maybe a simple plain alternative list append is enough.

**Comment by kopf** [comment]
Hi,

httsleep unfortunately doesn't support python 2.6 and I have no plans on dropping 2.7.x features in order to support it. I'm more concerned with making the code backwards compatible between 3.x and 2.7.x.
