### ISSUE TITLE
Remove convenience kwargs

### ISSUE THREAD

**Issue by kopf** [kopf/httsleep#6]
Deprecate and remove convenience kwargs (`status_code` etc), leaving just `until` and `alarms`

(hi @MathMagique - I've relented! ;) )

**Comment by MathMagique** [comment]
Aengus, you really made my day :-)

**Comment by kopf** [comment]
Hope you are doing well. Greetings to everyone in Karlsruhe! Have a lovely weekend & holiday :)

**Comment by MathMagique** [comment]
Thanks a lot, same to you!
